### PR TITLE
add Arlene

### PR DESCRIPTION
**Pull request by ahf00**

### CODE REVIEW

**Review by VesnaVucinic — APPROVED** [review]

**Review by VesnaVucinic — APPROVED** [review]

**Review by VesnaVucinic — CHANGES_REQUESTED** [review]
please make sure that you add name properly and not delete others , go back to you file and do all again

**Comment by Gingertonic** [comment]
> please make sure that you add name properly and not delete others , go back to you file and do all again

I think there might have been a misunderstanding - @ahf00 it looks like you didn't sync the latest changes before adding your name. We'll resolve this one our end and soon enough you'll be used to doing that sync for latest changes to make sure you've always got the most up to date content to work on!

**Review by Gingertonic — DISMISSED** [review]
Thanks Arlene, we'll handle the merge conflicts on this one - your student object is looking good though!

**Review by Gingertonic — COMMENTED** [review]
n/a

**Pull request merged**
