### PR TITLE
Changes to rooster

### PR DESCRIPTION
**Pull request by wotaque**

### CODE REVIEW

**Review by wotaque — COMMENTED** [review]
Added type CV

**Comment by wotaque** [comment]
Hi Romeo, I've just added the CV line but haveing an issue with other commits

**Comment by wotaque** [comment]
Added type Video

**Review by rom-30 — CHANGES_REQUESTED** [review]
Hi @wotaque,
I like the fact that you are trying to get ahead but please only add type: cv :)

**Comment by wotaque** [comment]
Hi @rom-30, Lily has asked us to do so

**Comment by rom-30** [comment]
you have to replace your-video-id with an actual id :)

**Comment by wotaque** [comment]
Added video ID

**Review by rom-30 — APPROVED** [review]
Thanks @wotaque

**Pull request merged**
