### PR TITLE
Isabel Repetto video added

### PR DESCRIPTION
**Pull request by neifors**

### CODE REVIEW

**Review by rom-30 — CHANGES_REQUESTED** [review]
@neifors 
We only need the endpoint of the youtube video
Can you please change to "url": "onU7e8U1l8"

**Comment by neifors** [comment]
I already modified the value of "url"

**Review by rom-30 — CHANGES_REQUESTED** [review]
This is definitely my fault as I typed instead of copying and pasting, but can you please change it to "_onU7e8U1l8" instead of "onU7e8U1l8"

**Comment by neifors** [comment]
Updated again =)

**Review by rom-30 — APPROVED** [review]
We got there in the end :) 
Thanks @neifors

**Pull request merged**
